version: "3.8"

services:
    app:
        container_name: hash-cart
        build: .
        command: npm start
        env_file:
            - .env
        ports:
            - "${API_PORT}:${API_PORT}"
        volumes:
            - .:/usr/app
        depends_on:
            - discount-service
        networks:
            - hash-network
    discount-service:
        container_name: discount-service
        image: hashorg/hash-mock-discount-service
        ports:
            - "50051:50051"
        networks:
            - hash-network

networks:
    hash-network:
        driver: bridge


